### ISSUE TITLE
Open Sauced

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#512]
Fri Nov 17, 2023 9am – 10am (EST)

- [x] cover image @codercatdev 
- [ ] purrfect picks @codercatdev
- [x] purrfect picks @brittneypostma 
- [x] streamyard updated on meeting @codercatdev 
- [x] podcast edited @ahmulder 
- [x] podcast live: youtube @ahmulder 
- [ ] podcast live: spotify @ahmulder 
- [ ] post update: slug @ahmulder 
- [x] post update: youtube @ahmulder 
- [ ] post update: spotify @ahmulder 
- [ ] review site @brittneypostma 
- [ ] pr merge @codercatdev or @brittneypostma

**Comment by codercatdev** [comment]
Page Preview: https://codingcat-dev-git-512-open-sauced-codercatdev.vercel.app/podcast/_opensauced
Guest Preview: https://codingcat-dev-git-512-open-sauced-codercatdev.vercel.app/guest/bekah-hawrot-weigel

@bekahhw just a reminder that we will be looking for "Purrfect Picks".

**Comment by BekahHW** [comment]
@codercatdev can I get the bio updated:

Bekah graduated from the Flatiron School Software Engineering program in May of 2019 and since then she has started a consultancy specializing in front-end development, created the developer community [Virtual Coffee](https://virtualcoffee.io/), spoken on podcasts and at conferences, and has continued to mom her four kids. She is currently the Developer Experience Lead at [OpenSauced](https://opensauced.pizza/).

Prior to tech, she spent 10 years teaching college English, three years organizing events and community, and fully embraces being a writer of many genres: code, blogs, short stories, non-fiction, screenplay, and curriculum.

**Comment by codercatdev** [comment]
@BekahHW latest
https://codingcat-i6gtrthfk-codercatdev.vercel.app/podcast/_opensauced

We also do something we call "purrfect picks" let me know and i can add that before the show. Just anything fun you might have seen lately. Netflix, amazon purchase, Lion's Win.

**Comment by BekahHW** [comment]
Sorry it took so long. I legit could not think of a purrfect pic. So much pressure 🤣

[Say my Name](https://saymyname.how/?ref=producthunt) is a service that allows you to record your name and send it to others so they can pronounce your name correctly.

**Comment by codercatdev** [comment]
Oh wow I love this!

**Comment by codercatdev** [comment]
@BekahHW we might need to update the title of this episode to include more about your journey

Additional links:

https://www.amazon.com/Working-Public-Making-Maintenance-Software/dp/0578675862

**Comment by BekahHW** [comment]
@

> @BekahHW we might need to update the title of this episode to include more about your journey


That's fine!
